//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnRhonline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SARHEntities : DbContext
    {
        public SARHEntities()
            : base("name=SARHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ligadetalle> ligadetalle { get; set; }
        public virtual DbSet<ligamaster> ligamaster { get; set; }
        public virtual DbSet<vep2> vep2 { get; set; }
    
        public virtual int actualizarregistro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizarregistro");
        }
    }
}
