//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnRhonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vep2
    {
        public Nullable<int> idhcm { get; set; }
        public string carnet { get; set; }
        public string carnet2 { get; set; }
        public string nombre_completo { get; set; }
        public string nom_jefe1 { get; set; }
        public string correo_jefe1 { get; set; }
        public string cargo_jefe1 { get; set; }
        public Nullable<int> idhcm_jefe1 { get; set; }
        public string carnet_jefe1 { get; set; }
        public Nullable<long> o1 { get; set; }
        public string nom_jefe2 { get; set; }
        public string correo_jefe2 { get; set; }
        public string cargo_jefe2 { get; set; }
        public Nullable<int> idhcm_jefe2 { get; set; }
        public string carnet_jefe2 { get; set; }
        public Nullable<long> o2 { get; set; }
        public string nom_jefe3 { get; set; }
        public string correo_jefe3 { get; set; }
        public string cargo_jefe3 { get; set; }
        public Nullable<int> idhcm_jefe3 { get; set; }
        public string carnet_jefe3 { get; set; }
        public Nullable<long> o3 { get; set; }
        public string nom_jefe4 { get; set; }
        public string correo_jefe4 { get; set; }
        public string cargo_jefe4 { get; set; }
        public Nullable<int> idhcm_jefe4 { get; set; }
        public string carnet_jefe4 { get; set; }
        public Nullable<long> o4 { get; set; }
        public string SUBGERENTECORREO { get; set; }
        public string SUBGERENTE { get; set; }
        public string GERENTECORREO { get; set; }
        public string GERENTE { get; set; }
        public string GERENTECARNET { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public string pais { get; set; }
        public Nullable<long> organizacion { get; set; }
        public string correo { get; set; }
        public string cargo { get; set; }
        public string empresa { get; set; }
        public string cedula { get; set; }
        public Nullable<long> jefe { get; set; }
        public int userlevel { get; set; }
        public long idorg { get; set; }
        public string primernivel { get; set; }
        public string nivel { get; set; }
        public Nullable<long> padre { get; set; }
        public string segundo_nivel { get; set; }
        public string tercer_nivel { get; set; }
        public string cuarto_nivel { get; set; }
        public string quinto_nivel { get; set; }
        public string sexto_nivel { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public string Expr1 { get; set; }
        public string Nombreubicacion { get; set; }
        public string datos { get; set; }
        public string Idhrms { get; set; }
        public Nullable<int> LVL { get; set; }
        public Nullable<int> userlvl { get; set; }
        public string oDEPARTAMENTO { get; set; }
        public string OGERENCIA { get; set; }
        public string oSUBGERENCIA { get; set; }
    }
}
